GUFO_OVERVIEW_PATTERNS = [
    ("1. Usage Scenarios", "Every person is an object[gufo]."),
    ("1. Usage Scenarios", "Person is a kind[gufo]."),
    ("Key Patterns for LLMs", "Every person is an object[gufo]."),
    ("Key Patterns for LLMs", "Person is a kind[gufo]."),
    ("Key Patterns for LLMs", "Every person has-age some value."),
    ("Key Patterns for LLMs", "Every-single-thing has-age nothing-but integer values."),
    ("Key Patterns for LLMs", "Every person has-weight-kg some value."),
    ("Key Patterns for LLMs", "Every weight is a quality[gufo]."),
    ("Key Patterns for LLMs", "Every weight inheres-in[gufo] exactly-one person."),
    ("Key Patterns for LLMs", "Every weight has-quality-value[gufo] some value."),
    ("Key Patterns for LLMs", "Every person knows some person."),
    ("Key Patterns for LLMs", "Every friendship is a relator[gufo]."),
    ("Key Patterns for LLMs", "Every friendship mediates[gufo] exactly 2 persons."),
    ("Key Patterns for LLMs", "Every friendship has-begin-date[gufo] some value."),
    ("2.1. Concrete Individuals", "The-1985-Mexico-City-Earthquake is an event[gufo] and has-begin-date[gufo] equal-to 1985-09-19T131750Z."),
    ("2.1. Concrete Individuals", "Every earthquake is an event[gufo]."),
    ("2.1. Concrete Individuals", "The-1985-Mexico-City-Earthquake is an earthquake and has-begin-date[gufo] equal-to 1985-09-19T131750Z."),
    ("2.2. Objects and their parts", "John is a person."),
    ("2.2. Objects and their parts", "Every brain is an object[gufo]."),
    ("2.2. Objects and their parts", "Johns-Brain is a brain and is-component-of[gufo] John."),
    ("2.3. Intrinsic Aspects", "Every physical-object has-mass-in-kilograms some value."),
    ("2.3. Intrinsic Aspects", "Moon is a physical-object and has-mass-in-kilograms equal-to 7.34767309E22."),
    ("2.4. Qualities - Basic pattern", "Every mass is a quality[gufo]."),
    ("2.4. Qualities - Basic pattern", "Moon is a physical-object."),
    ("2.4. Qualities - Basic pattern", "Moon-Mass is a mass that inheres-in[gufo] Moon and has-quality-value[gufo] equal-to 7.34767309E22."),
    ("2.4. Qualities - Basic pattern", "Every mass inheres-in[gufo] exactly-one physical-object."),
    ("2.4. Qualities - Basic pattern", "If X is-mass-of Y then X inheres-in[gufo] Y."),
    ("2.4. Qualities - Basic pattern", "Every mass is-mass-of something."),
    ("2.4. Qualities - Basic pattern", "Every-single-thing is-mass-of nothing-but physical-objects."),
    ("2.4. Qualities - Basic pattern", "If X has-mass-in-kilograms equal-to Y then X has-quality-value[gufo] equal-to Y."),
    ("2.4. Qualities - Basic pattern", "Every mass has-mass-in-kilograms some value."),
    ("2.4. Qualities - Basic pattern", "If X has-mass-in-short-tons equal-to Y then X has-quality-value[gufo] equal-to Y."),
    ("2.4. Qualities - Basic pattern", "Every mass has-mass-in-short-tons some value."),
    ("2.4. Qualities - Basic pattern", "Moons-Mass is a mass and is-mass-of Moon and has-mass-in-kilograms equal-to 7.34767309E22 and has-mass-in-short-tons equal-to 8.099423160000001E19."),
    ("2.5. Qualities - Advanced usage", "Something is a shirt-size if-and-only-if-it is a quality-value[gufo] and is either S , M, L or XL."),
    ("2.5. Qualities - Advanced usage", "S is a shirt-size ."),
    ("2.5. Qualities - Advanced usage", "M is a shirt-size ."),
    ("2.5. Qualities - Advanced usage", "L is a shirt-size ."),
    ("2.5. Qualities - Advanced usage", "XL is a shirt-size ."),
    ("2.5. Qualities - Advanced usage", "Every color-value-in-rgb is a quality-value[gufo]."),
    ("2.5. Qualities - Advanced usage", "If X has-color-value-in-rgb Y then X has-reified-quality-value[gufo] Y."),
    ("2.5. Qualities - Advanced usage", "Every color has-color-value-in-rgb something."),
    ("2.5. Qualities - Advanced usage", "Every-single-thing has-color-value-in-rgb nothing-but color-value-in-rgbs ."),
    ("2.5. Qualities - Advanced usage", "If X has-red-value-component equal-to Y then X has-value-component[gufo] equal-to Y."),
    ("2.5. Qualities - Advanced usage", "Every color-value-in-rgb has-red-value-component (some value)."),
    ("2.5. Qualities - Advanced usage", "Every-single-thing has-red-value-component nothing-but (some integer value)."),
    ("2.5. Qualities - Advanced usage", "If X has-green-value-component equal-to Y then X has-value-component[gufo] equal-to Y."),
    ("2.5. Qualities - Advanced usage", "Every color-value-in-rgb has-green-value-component (some value)."),
    ("2.5. Qualities - Advanced usage", "Every-single-thing has-green-value-component nothing-but (some integer value)."),
    ("2.5. Qualities - Advanced usage", "If X has-blue-value-component equal-to Y then X has-value-component[gufo] equal-to Y."),
    ("2.5. Qualities - Advanced usage", "Every color-value-in-rgb has-blue-value-component (some value)."),
    ("2.5. Qualities - Advanced usage", "Every-single-thing has-blue-value-component nothing-but (some integer value)."),
    ("2.5. Qualities - Advanced usage", "Yves-Klein-Blue-Monochrome-Painting is a physical-object."),
    ("2.5. Qualities - Advanced usage", "Yves-Klein-Blue-Monochrome-Painting-Color is a color and inheres-in[gufo] Yves-Klein-Blue-Monochrome-Painting and has-color-value-in-rgb Yves-Klein-Blue-Monochrome-Painting-Color-Value-In-Rgb."),
    ("2.5. Qualities - Advanced usage", "Yves-Klein-Blue-Monochrome-Painting-Color-Value-In-Rgb is a color-value-in-rgb that has-red-value-component equal-to 0 and has-green-value-component equal-to 47 and has-blue-value-component equal-to 167."),
    ("2.6. Intrinsic Modes", "Every headache is an intrinsic-mode[gufo]."),
    ("2.6. Intrinsic Modes", "If X is-headache-of Y then X inheres-in[gufo] Y."),
    ("2.6. Intrinsic Modes", "Every headache is-headache-of something ."),
    ("2.6. Intrinsic Modes", "Every-single-thing is-headache-of nothing-but person."),
    ("2.6. Intrinsic Modes", "Johns-Headache is a headache and is-headache-of John and has-begin-date[gufo] equal-to 2019-11-19T141450Z."),
    ("2.6. Intrinsic Modes", "Every headache-intensity is a quality[gufo]."),
    ("2.6. Intrinsic Modes", "Johns-Headache-Intensity is a headache-intensity and inheres-in[gufo] Johns-Headache and has-quality-value[gufo] equal-to 2."),
    ("2.7. Extrinsic Aspects", "Every marriage is a relator[gufo]."),
    ("2.7. Extrinsic Aspects", "If X marriage-involves Y then X mediates[gufo] Y."),
    ("2.7. Extrinsic Aspects", "Every marriage marriage-involves something ."),
    ("2.7. Extrinsic Aspects", "Every-single-thing marriage-involves nothing-but person."),
    ("2.7. Extrinsic Aspects", "John is a person."),
    ("2.7. Extrinsic Aspects", "Mary is a person."),
    ("2.7. Extrinsic Aspects", "John-Mary-Marriage is a marriage and marriages-involves John and marriages-involves Mary."),
    ("2.7. Extrinsic Aspects", "Every employment is a relator[gufo]."),
    ("2.7. Extrinsic Aspects", "Every employee is a person."),
    ("2.7. Extrinsic Aspects", "Every organization is an object[gufo]."),
    ("2.7. Extrinsic Aspects", "Every employer is an organization ."),
    ("2.7. Extrinsic Aspects", "If X involves-employee Y then X mediates[gufo] Y."),
    ("2.7. Extrinsic Aspects", "Every employment involves-employee something ."),
    ("2.7. Extrinsic Aspects", "Every-single-thing involves-employee nothing-but employees."),
    ("2.7. Extrinsic Aspects", "If X involves-employer Y then X mediates[gufo] Y."),
    ("2.7. Extrinsic Aspects", "Every employment involves-employer something ."),
    ("2.7. Extrinsic Aspects", "Every-single-thing involves-employer nothing-but employers."),
    ("2.7. Extrinsic Aspects", "Every marriage mediates[gufo] a person."),
    ("2.7. Extrinsic Aspects", "Amazon-Inc is organization."),
    ("2.7. Extrinsic Aspects", "Every service-agreement is a relator[gufo]."),
    ("2.7. Extrinsic Aspects", "John-Amazon-Agreement is a service-agreement that mediates[gufo] Amazon-Inc and mediates[gufo] John."),
    ("2.7. Extrinsic Aspects", "Johns-Right-To-Service-Provisioning is an extrinsic-mode[gufo] that inheres-in[gufo] John and depends-externally-on[gufo] Amazon-Inc and is-aspect-proper-part-of[gufo] John-Amazon-Agreement."),
    ("2.7. Extrinsic Aspects", "Amazons-Duty-To-Provide-Service is an extrinsic-mode[gufo] that inheres-in[gufo] Amazon-Inc and depends-externally-on[gufo] John and is-aspect-proper-part-of[gufo] John-Amazon-Agreement."),
    ("2.7. Extrinsic Aspects", "Amazons-Right-To-Payment is an extrinsic-mode[gufo] that inheres-in[gufo] Amazon-Inc and depends-externally-on[gufo] John and is-aspect-proper-part-of[gufo] John-Amazon-Agreement."),
    ("2.7. Extrinsic Aspects", "Johns-Duty-To-Pay is an extrinsic-mode[gufo] that inheres-in[gufo] John and depends-externally-on[gufo] Amazon-Inc and is-aspect-proper-part-of[gufo] John-Amazon-Agreement."),
    ("2.8. Events", "Every natural-disaster is an event[gufo]."),
    ("2.8. Events", "Every earthquake is a natural-disaster."),
    ("2.8. Events", "No earthquake is a tsunami."),
    ("2.8. Events", "Every tsunami is a natural-disaster."),
    ("2.8. Events", "Every soccer-match is an event[gufo]."),
    ("2.8. Events", "World-Cup-1970-Final is a soccer-match ."),
    ("2.8. Events", "World-Cup-1970-Final depends-historically-on[gufo] Brazil-Uruguay-World-Cup-1970-Semi-Final."),
    ("2.8. Events", "World-Cup-1970-Final depends-historically-on[gufo] Italy-West-Germany-World-Cup-1970-Semi-Final."),
    ("2.8. Events", "Every soccer-match-player is a person."),
    ("2.8. Events", "If X participates-in-match Y then X participates-in[gufo] Y."),
    ("2.8. Events", "Every soccer-match-player participates-in-match something ."),
    ("2.8. Events", "Every-single-thing participates-in-match nothing-but soccer-matches."),
    ("2.8. Events", "Pele is a person that participates-in-match World-Cup-1970-Final."),
    ("2.8. Events", "World-Cup-1970 is an event[gufo]."),
    ("2.8. Events", "World-Cup-1970-Final is a soccer-match that is-event-proper-part-of[gufo] World-Cup-1970."),
    ("2.8. Events", "John-Marys-Marriage is a marriage that marriage-involves John and marriage-involves Mary and is-created-in[gufo] John-Marys-Wedding."),
    ("2.8. Events", "John-Marys-Wedding is an event[gufo] that has-begin-date[gufo] equal-to 2001-12-12 and has-end-date[gufo] equal-to 2001-12-12."),
    ("2.8. Events", "Challenger is a functional-complex[gufo] that is-terminated-in[gufo] Challengers-10-Th-Flight."),
    ("2.8. Events", "Challengers-10-Th-Flight is an event[gufo] that has-begin-date[gufo] equal-to 1986-01-28 and has-end-date[gufo] equal-to 1986-01-28."),
    ("2.8. Events", "Challenger-Right-Booster-Seal is a functional-complex[gufo] that is-component-of[gufo] Challenger."),
    ("2.8. Events", "Challenger-Right-Booster-Seal-Flaw is an intrinsic-mode[gufo] that inheres-in[gufo] Challenger-Right-Booster-Seal and is-manifested-in[gufo] Challengers-10-Th-Launch."),
    ("2.9. Situations", "John-Weighs-80-Kgin-2015 is a quality-value-attribution-situation[gufo] that concerns-quality-type[gufo] Mass and concerns-quality-value[gufo] equal-to 80.0 and has-begin-date[gufo] equal-to 2015-01-01 and has-end-date[gufo] equal-to 2015-12-31."),
    ("2.9. Situations", "John-Weighs-70-Kgin-2018 is a quality-value-attribution-situation[gufo] that concerns-quality-type[gufo] Mass and concerns-quality-value[gufo] equal-to 70.0 and has-begin-date[gufo] equal-to 2018-01-01 and has-end-date[gufo] equal-to 2018-12-31."),
    ("2.9. Situations", "John stands-in-qualified-attribution[gufo] John-Weighs-80-Kgin-2015 and stands-in-qualified-attribution[gufo] John-Weighs-70-Kgin-2018 ."),
    ("2.9. Situations", "Every child is a person."),
    ("2.9. Situations", "Every adult is a person."),
    ("2.9. Situations", "John-Was-A-Child-From-1977-To-1995 is a temporary-instantiation-situation[gufo] that concerns-non-rigid-type[gufo] Child and has-begin-date[gufo] equal-to 1977-10-01 and has-end-date[gufo] equal-to 1995-09-31."),
    ("2.9. Situations", "John-Is-Adult-From-1995 is a temporary-instantiation-situation[gufo] that concerns-non-rigid-type[gufo] Adult and has-begin-date[gufo] equal-to 1995-10-01."),
    ("2.9. Situations", "Johns-Heart is a heart that stands-in-qualified-parthood[gufo] John-Has-Original-Heart and stands-in-qualified-parthood[gufo] Paul-Has-Johns-Heart."),
    ("2.9. Situations", "Pauls-Heart is a heart that stands-in-qualified-parthood[gufo] Paul-Has-Original-Heart."),
    ("2.9. Situations", "John-Has-Original-Heart is a temporary-parthood-situation[gufo] that concerns-temporary-whole[gufo] John and has-end-date[gufo] equal-to 2018-11-01."),
    ("2.9. Situations", "Paul-Has-Original-Heart is a temporary-parthood-situation[gufo] that concerns-temporary-whole[gufo] Paul and has-end-date[gufo] equal-to 2018-11-01."),
    ("2.9. Situations", "Paul-Has-Johns-Heart is a temporary-parthood-situation[gufo] that concerns-temporary-whole[gufo] Paul and has-begin-date[gufo] equal-to 2018-11-01."),
    ("2.9. Situations", "Venus-Of-Milo is a statue."),
    ("2.9. Situations", "Original-Quantity-Of-Marble is an amount-of-marble that stands-in-qualified-constitution[gufo] Venus-Has-Arms."),
    ("2.9. Situations", "Reduced-Quantity-Of-Marble is an amount-of-marble that stands-in-qualified-constitution[gufo] Venus-Has-No-Arms."),
    ("2.9. Situations", "Venus-Has-Arms is a temporary-constitution-situation[gufo] that concerns-constituted-endurant[gufo] Venus-Of-Milo and has-end-date[gufo] equal-to 1820-01-01."),
    ("2.9. Situations", "Venus-Has-No-Arms is a temporary-constitution-situation[gufo] that concerns-constituted-endurant[gufo] Venus-Of-Milo and has-end-date[gufo] equal-to 1820-01-02."),
    ("2.9. Situations", "Every physical-object is-heavier-than something."),
    ("2.9. Situations", "Every-single-thing is-heavier-than nothing-but physical-objects."),
    ("2.9. Situations", "John is a physical-object."),
    ("2.9. Situations", "Paul is a physical-object."),
    ("2.9. Situations", "John stands-as-heavier-object[gufo] John-Is-Heavier."),
    ("2.9. Situations", "John-Is-Heavier is a temporary-relationship-situation[gufo] that concerns-relationship-type[gufo] Is-Heavier-Than and concerns-lighter-object Paul and has-begin-date[gufo] equal-to 2019-05-30 and has-end-date[gufo] equal-to 2019-05-30."),
    ("2.9. Situations", "If X stands-as-heavier-object Y then X stands-in-qualified-relationship[gufo] Y."),
    ("2.9. Situations", "If X concerns-lighter-object Y then X concerns-related-endurant[gufo] Y."),
    ("2.9. Situations", "Every transplant is an event[gufo]."),
    ("2.9. Situations", "John-To-Paul-Heart-Transplant is a transplant and is-brought-about-by[gufo] Paul-Has-Johns-Heart."),
    ("2.9. Situations", "Every security-incident is an event[gufo]."),
    ("2.9. Situations", "Wanna-Cry-Ransomware-Attack-On-Host-1234 is a security-incident that has-begin-date[gufo] equal-to 2017-05-12 and has-end-date[gufo] equal-to 2017-05-13."),
    ("2.9. Situations", "Every computer-system is an object[gufo]."),
    ("2.9. Situations", "Host-1234 is a computer-system that participates-in[gufo] Wanna-Cry-Ransomware-Attack-On-Host-1234."),
    ("2.9. Situations", "Every vulnerable-system is an object[gufo]."),
    ("2.9. Situations", "Host-1234-Vulnerable-12-May-2017 is a temporary-instantiation-situation[gufo] that concerns-non-rigid-type[gufo] Vulnerable-System and has-begin-date[gufo] equal-to 2017-05-12 and has-end-date[gufo] equal-to 2017-05-12 and contributes-to-trigger[gufo] Wanna-Cry-Ransomware-Attack-On-Host-1234."),
    ("3.1. Endurant types", "Person is a kind[gufo]."),
    ("3.1. Endurant types", "Adult is a phase[gufo]."),
    ("3.1. Endurant types", "Every adult is a person."),
    ("3.1. Endurant types", "Student is a role[gufo]."),
    ("3.1. Endurant types", "Every student is a person."),
    ("3.2. Relationship types", "Is-Married-With is a material-relationship-type[gufo]."),
    ("3.2. Relationship types", "Every person is-married-with something."),
    ("3.2. Relationship types", "Every-single-thing is-married-with nothing-but persons."),
    ("3.2. Relationship types", "Is-Married-With is-derived-from[gufo] Marriage."),
    ("3.3. High-order types", "Person-Role categorizes[gufo] Person."),
    ("3.3. High-order types", "Every person-role is a role[gufo]."),
    ("3.3. High-order types", "Student is a person-role."),
    ("3.3. High-order types", "Every student is a person."),
    ("3.3. High-order types", "Professor is a person-role ."),
    ("3.3. High-order types", "Every professor is a person."),
    ("3.3. High-order types", "Ship-Type categorizes[gufo] Ship."),
    ("3.3. High-order types", "Every ship-type is a sub-kind[gufo]."),
    ("3.3. High-order types", "Supercarrier is a ship-type."),
    ("3.3. High-order types", "Every supercarrier is a ship."),
    ("3.3. High-order types", "Cargo-Ship is a ship-type ."),
    ("3.3. High-order types", "Every cargo-ship is a ship."),
    ("3.3. High-order types", "Animal-Species partitions[gufo] Animal."),
    ("3.3. High-order types", "Hiena is an animal-species."),
    ("3.3. High-order types", "Every hiena is an animal."),
    ("3.3. High-order types", "Lion is an animal-species."),
    ("3.3. High-order types", "Every lion is an animal."),
    ("3.3. High-order types", "No lion is a hiena."),
    ("3.3. High-order types", "Cecil is a lion."),
]
# Total: 169 patterns
